- name: Create the fluent group
  group:
    name: fluent
    gid: 101
    state: present

- name: Create the fluent user
  user:
    name: fluent
    group: fluent
    uid: 100
    state: present

- name: Create fluentd pos file directory
  file:
    state: directory
    path: /var/run/fluentd
    group: fluent
    owner: fluent

- name: Create fluentd config file
  copy:
    src: fluent.conf
    dest: "{{ node_config_directory }}/fluent.conf"
  notify: Restart fluentd container

- name: Create fluentd container
  docker_container:
    name: "fluentd"
    image: "{{ fluentd_image }}"
    network_mode: host
    restart_policy: always
    volumes:
      - "/var/log:/var/log"
      - "{{ node_config_directory }}/fluent.conf:/fluentd/etc/fluent.conf"
      - "/var/run/fluentd:/var/run/fluentd"
